services:
  memcached:
    extends:
      file: compose.yaml
      service: memcached

  # redis:
  #   extends:
  #     file: compose.yaml
  #     service: redis

  # ftp:
  #   extends:
  #     file: compose.yaml
  #     service: ftp

  # mysql:
  #   extends:
  #     file: compose.yaml
  #     service: mysql

  mariadb:
    extends:
      file: compose.yaml
      service: mariadb

  postgres:
    extends:
      file: compose.yaml
      service: postgres

  adminer:
    extends:
      file: compose.yaml
      service: adminer

  php-fpm:
    extends:
      file: compose.yaml
      service: php-fpm

  smf:
    extends:
      file: compose.yaml
      service: smf

  nginx:
    image: bitnami/nginx
    container_name: ${APP_NAME}_nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./_docker/nginx/default.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf:ro
      - ./_docker/certs:/certs
      - web:/app
    depends_on:
      - mariadb
      - smf

volumes:
  redis:
  mysql:
  pgsql:
  web:
