services:

  memcached:
    image: memcached:alpine
    container_name: ${APP_NAME}_memcached

  # redis:
  #   image: redis:alpine
  #   container_name: ${APP_NAME}_redis
  #   command: redis-server /usr/local/etc/redis/redis.conf
  #   restart: always
  #   volumes:
  #     - redis:/data
  #     - ./_docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   environment:
  #     REDIS_USERNAME: ${REDIS_USERNAME}
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}

  # ftp:
  #   image: stilliard/pure-ftpd
  #   container_name: ${APP_NAME}_ftp
  #   restart: always
  #   environment:
  #     PUBLICHOST: localhost
  #     FTP_USER_NAME: user
  #     FTP_USER_PASS: pass
  #     FTP_USER_HOME: /app
  #   volumes:
  #     - ftp:/etc/pure-ftpd/passwd
  #     - ftp:/home/ftpusers
  #     - web:/app
  #   ports:
  #     - "21:21"
  #     - "30000-30009:30000-30009"
  #   depends_on:
  #     - smf

  # mysql:
  #   image: mysql
  #   container_name: ${APP_NAME}_mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASS}

  mariadb:
    image: mariadb
    container_name: ${APP_NAME}_mariadb
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}

  postgres:
    image: 'postgres:alpine'
    container_name: ${APP_NAME}_postgres
    restart: always
    volumes:
      - pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  adminer:
    image: adminer
    container_name: ${APP_NAME}_adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: lucas-sandery
    ports:
      - 8080:8080
    depends_on:
      - mariadb
      - postgres

  php-fpm:
    build:
      context: ./_docker/php-fpm
      args:
        PHP_VERSION: ${PHP_VERSION}
        SMF_VERSION: ${SMF_VERSION}
      target: backend
    container_name: ${APP_NAME}_php_fpm
    working_dir: /app
    restart: always
    volumes:
      - web:/app
      - ./_docker/php-fpm/php-ini-overrides.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/99-overrides.ini

  smf:
    build:
      context: ./_docker/php-fpm
      target: smf
    container_name: ${APP_NAME}_smf
    working_dir: /app
    volumes:
      - web:/app
    depends_on:
      - php-fpm

  apache:
    image: bitnami/apache
    container_name: ${APP_NAME}_apache
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./_docker/apache:/vhosts:ro
      #- ./_docker/certs:/certs
      - web:/app
      #- ./src:/app
    depends_on:
      - mariadb
      - smf

volumes:
  redis:
  mysql:
  pgsql:
  web:
