version: '3.8'

services:
    memcached:
        image: 'memcached:alpine'
        container_name: memcached

    mariadb:
        image: mariadb
        container_name: mariadb
        restart: always
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=smf
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        ports:
            - 3306:3306

    postgres:
        image: 'postgres:14-alpine'
        container_name: postgres
        restart: always
        volumes:
            - pgsql:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=smf
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
        ports:
            - 5432:5432

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        environment:
            - ADMINER_DEFAULT_SERVER=db
            - ADMINER_DESIGN=lucas-sandery
        ports:
            - 8080:8080
        depends_on:
            - mariadb
            - postgres

    web:
        image: 'nginx:alpine'
        container_name: web
        working_dir: /var/www/html
        volumes:
            - smf:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        links:
            - mariadb
            - postgres

    php-fpm:
        build: docker/php-fpm
        container_name: php
        working_dir: /var/www/html
        volumes:
            - smf:/var/www/html
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

volumes:
    smf:
    mysql:
    pgsql: