services:
  memcached:
    extends:
      file: compose.yaml
      service: memcached

  # redis:
  #   extends:
  #     file: compose.yaml
  #     service: redis

  # ftp:
  #   extends:
  #     file: compose.yaml
  #     service: ftp

  # mysql:
  #   extends:
  #     file: compose.yaml
  #     service: mysql

  mariadb:
    extends:
      file: compose.yaml
      service: mariadb

  postgres:
    extends:
      file: compose.yaml
      service: postgres

  adminer:
    extends:
      file: compose.yaml
      service: adminer

  php-fpm:
    extends:
      file: compose.yaml
      service: php-fpm

  smf:
    extends:
      file: compose.yaml
      service: smf

  nginx:
    build:
      context: .
      dockerfile: _docker/nginx/Dockerfile
    container_name: ${APP_NAME}_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - web:/app
      - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mariadb
      - smf

volumes:
  redis:
  mysql:
  pgsql:
  web:
